---
title: "Exploratory Analysis on Iris Dataset"
output:
  word_document: default
  html_notebook: default
---

# Overview

## 6 point summary of full dataset

```{r,echo = FALSE}
plot(iris);grid()
print("----------------Data Summary------------------------")

summary(iris)


vartype = 1:ncol(iris)
for(i in 1:ncol(iris)){
  vartype[i] = as.character(class(iris[,i]))
}
print("----------------Type of variable------------------------")

#for(i in 1:ncol(iris)) print(paste(colnames(iris[i]),vartype[i],sep = " is "))
n_cat = 0
i_cat = c();i_num=c()
for(i in 1:ncol(iris)){
  if(vartype[i]=="character" | vartype[i] == "factor"){
    n_cat = n_cat+1
    i_cat =  c(i_cat,i)
  }else{
    i_num = c(i_num,i)
  }
}
n_num =as.integer(ncol(iris)-n_cat)
print(paste("There are",n_num,"numerical variables:"))
print(paste(colnames(iris)[i_num],collapse = '||'))
print(paste("; and ",n_cat,"categorical variables."))
print(paste(colnames(iris)[i_cat],collapse = '||'))
print("----------------Data Structure------------------------")

str(iris)
```

## 1 and 2 variable plots

```{r,echo = FALSE}
if(n_cat>=1){
  for(i in 1:n_cat){
    library(lattice)
    plot(iris[,i_num],col = iris[,i_cat[i]])
    title(paste( "Plot Matrix by",colnames(iris)[i_cat[i]]))
    library(ggplot2)
    library(GGally)
    g=GGally::ggpairs(iris,aes(fill =eval(parse(text = colnames(iris)[i_cat[i]])),color = eval(parse(text = colnames(iris)[i_cat[i]])),alpha=.5))
    print(g)
    ggsave(paste("DataMatrix_",colnames(iris)[i_cat[i]],'.png'),width = 20,height=12)
    g2 =ggparcoord(iris,groupColumn = i_cat[i])
    print(g2)
    ggsave(paste("DataParCoord_",colnames(iris)[i_cat[i]],'.png'),width = 20,height=12)
  }
}
```

## 1D Distribution with normal curve

```{r, echo = FALSE}


Skewness =function(x){
  m = mean(x)
  n = length(x)
  s = sd(x)
  sum((x-m)^3/s^3)/n
}
abline_summary = function(x,type = 'v'){
  L = list(list(mean(x),col = "green"),
           list(median(x),col = "blue"),
           list(quantile(x,.25),col = "brown"),
           list(quantile(x,.75),col = "brown"),
           list(quantile(x,.05),col = "purple"),
           list(quantile(x,.95),col = "purple"))
  for(i in 1:length(L)){
    x = L[[i]]
    names(x)[1] = type
    do.call(abline,x)
  }
}
#hence write a function that add normal density line to certain dataset

lines_dnorm = function(x,n=20){
  xbase = seq(from=min(x),to=max(x),length.out=n)
  lines(xbase,dnorm(xbase,mean = mean(x),sd =sd(x)),col='blue',lty=2)
}

for(i in 1:n_num){
  plot(density(iris[,i_num[i]]),col = 'red',lty=2,main =paste0("Distribution of ",colnames(iris)[i_num[i]]," ","with fitted normal curve",sep = " "))

lines_dnorm(iris[,i_num[i]])
abline_summary(iris[,i_num[i]])
#add grid
grid()
print("----------------Skewness factor and Normality test-----------------")
print("Skewness:")
print(Skewness(iris[,i_num[i]]))
print("Shapiro test")
print(shapiro.test(iris[,i_num[i]]))
print('------------------Other discriptive Mtds-----------------------')

print(Hmisc::describe(iris[,i_num[i]]))
print(psych::describe(iris[,i_num[i]]))
pastecs::stat.desc(iris[,i_num[i]],basic = T,
                   desc = F,
                   norm = F)
pastecs::stat.desc(iris[,i_num[i]],basic =F,
                   desc = T,
                   norm = F)
pastecs::stat.desc(iris[,i_num[i]],basic =F,
                   desc = F,
                   norm = T)
qqnorm(iris[,i_num[i]]);grid()
}

```


## Distribution w.r.t categorical var, and analysis of variance
using AOV test

```{r, echo = FALSE}
library(lattice)
if(n_cat>=1){
  for(i in 1:n_cat){
    for(j in 1:n_num){
      g=ggplot(data=iris,aes(x=eval(parse(text=colnames(iris)[i_num[j]])),fill = eval(parse(text = colnames(iris)[i_cat[i]])))) + 
  geom_histogram(position = 'identity',alpha=.5)+geom_rug()+labs(x =colnames(iris)[i_num[j]] ,fill= colnames(iris)[i_cat[i]])
      print(g)
      print(ggplot(data=iris,aes(x=eval(parse(text=colnames(iris)[i_num[j]])),fill = eval(parse(text = colnames(iris)[i_cat[i]])))) +geom_density(alpha = .3)+labs(x =colnames(iris)[i_num[j]] ,fill= colnames(iris)[i_cat[i]]))
      print(bwplot(as.formula(paste(colnames(iris)[i_num[j]], colnames(iris)[i_cat[i]],sep = '~')),iris))
      aov_result = aov(as.formula(paste(colnames(iris)[i_num[j]], colnames(iris)[i_cat[i]],sep = '~')),iris)
      print("-------------Analysis of Variance-----------------")
      print(paste(colnames(iris)[i_num[j]], colnames(iris)[i_cat[i]],sep = '~'))
      ## todo: validation
      print(aov_result)
      ## todo: explanation
      }
    
  }
}
#?aov
#lattice::bwplot(Petal.Width ~ Species,iris)

```



## 1v1 linear correlations

```{r,echo = FALSE}
(cor_result = cor(iris[,i_num]))
symnum(cor_result)
library(ggcorrplot)
library(RColorBrewer)
ggcorrplot(cor(iris[i_num]),method='square',color =c("blue","green","red"))
```




## 1v1 linear regression

```{r plot,echo = FALSE}
if(n_num>=2){
  for(i in 1:(n_num-1)){
    for(j in (i+1):n_num){
      yname = colnames(iris)[i_num[j]]
      xname = colnames(iris)[i_num[i]]
      g = ggplot(data = iris,aes(x =eval(parse(text = xname)),y =eval(parse(text = yname)))) +geom_point(alpha = .5)+ geom_rug(alpha = .5) + geom_smooth(method = 'lm',color = "red")+geom_smooth(color ="blue")+labs(x =xname,y = yname )
      print(g)
      print("---------------Linear Regression Model----------------")
      
      print(paste(yname,xname,sep = "~"))
      model = lm(as.formula(paste(yname,xname,sep = "~")),data = iris)
      print(summary(model))
      print(model)
    }
  }
}

```


## 1v1 regression by category


```{r,echo = FALSE} 

if(n_num>=2){
  for(k in 1:n_cat){
  for(i in 1:(n_num-1)){
    for(j in (i+1):n_num){
      yname = colnames(iris)[i_num[j]]
      xname = colnames(iris)[i_num[i]]
      cat_name = colnames(iris)[i_cat[k]]
      g = ggplot(data = iris,aes(x =eval(parse(text = xname)),y =eval(parse(text = yname)))) + facet_grid(eval(parse(text = paste0(".~",cat_name))))+geom_point(aes(color = eval(parse(text = cat_name)),shape= eval(parse(text = cat_name))),alpha=.5)+ geom_rug(alpha = .5) + geom_smooth(method = 'lm',color = "red")+geom_smooth(color ="blue")+labs(x =xname,y = yname,color = cat_name,shape = cat_name)
      print(g)
      g2 = ggplot(data = iris,aes(x =eval(parse(text = xname)),y =eval(parse(text = yname))),group =eval(parse(text = cat_name))) +geom_point(aes(color = eval(parse(text = cat_name)),shape= eval(parse(text = cat_name))),alpha=.5)+ geom_rug(alpha = .5) + geom_smooth(aes(group =eval(parse(text = cat_name))),method = 'lm',color = "red")+geom_smooth(aes(group =eval(parse(text = cat_name))),color ="blue")+labs(x =xname,y = yname,color = cat_name,shape = cat_name)
      print(g2)
      print("---------------Linear Regression Model----------------")
  
    }
  }
  }
}#g1 = g + geom_point(aes(color = Species,shape= Species))

    #  g1 = g1+ facet_grid(.~Species)
```


## 3D plots


```{r,echo = FALSE}
#install.packages("plot3D")
library(plot3D)

if(n_num>=3 && n_cat>=1){
  for(a in 1:n_cat){
    for(x in 1:(n_num-2)){
      for(y in (x+1):(n_num-1)){
        for(z in (y+1):(n_num)){
          xname = colnames(iris)[i_num[x]]
          yname = colnames(iris)[i_num[y]]
          zname = colnames(iris)[i_num[z]]
          cname = colnames(iris)[i_cat[a]]
          plot3D::scatter3D(iris[,i_num[x]],iris[,i_num[y]],iris[,i_num[z]],
                  col= as.numeric(iris[,i_cat[a]]),
                  xlab =xname,
                  ylab =yname,
                  zlab =zname)
          }
      }
    }
  }
  
}

```

End of exploratory analysis paper